// Generated by gencpp from file my_ros_package/AddOneResponse.msg
// DO NOT EDIT!


#ifndef MY_ROS_PACKAGE_MESSAGE_ADDONERESPONSE_H
#define MY_ROS_PACKAGE_MESSAGE_ADDONERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_ros_package
{
template <class ContainerAllocator>
struct AddOneResponse_
{
  typedef AddOneResponse_<ContainerAllocator> Type;

  AddOneResponse_()
    : output(0)  {
    }
  AddOneResponse_(const ContainerAllocator& _alloc)
    : output(0)  {
  (void)_alloc;
    }



   typedef int32_t _output_type;
  _output_type output;





  typedef boost::shared_ptr< ::my_ros_package::AddOneResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_ros_package::AddOneResponse_<ContainerAllocator> const> ConstPtr;

}; // struct AddOneResponse_

typedef ::my_ros_package::AddOneResponse_<std::allocator<void> > AddOneResponse;

typedef boost::shared_ptr< ::my_ros_package::AddOneResponse > AddOneResponsePtr;
typedef boost::shared_ptr< ::my_ros_package::AddOneResponse const> AddOneResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_ros_package::AddOneResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_ros_package::AddOneResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_ros_package::AddOneResponse_<ContainerAllocator1> & lhs, const ::my_ros_package::AddOneResponse_<ContainerAllocator2> & rhs)
{
  return lhs.output == rhs.output;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_ros_package::AddOneResponse_<ContainerAllocator1> & lhs, const ::my_ros_package::AddOneResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_ros_package

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_ros_package::AddOneResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_ros_package::AddOneResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_ros_package::AddOneResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_ros_package::AddOneResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_ros_package::AddOneResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_ros_package::AddOneResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_ros_package::AddOneResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d5fc6b37f5643970fe87c91f31f11e4a";
  }

  static const char* value(const ::my_ros_package::AddOneResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd5fc6b37f5643970ULL;
  static const uint64_t static_value2 = 0xfe87c91f31f11e4aULL;
};

template<class ContainerAllocator>
struct DataType< ::my_ros_package::AddOneResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_ros_package/AddOneResponse";
  }

  static const char* value(const ::my_ros_package::AddOneResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_ros_package::AddOneResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 output\n"
"\n"
;
  }

  static const char* value(const ::my_ros_package::AddOneResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_ros_package::AddOneResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.output);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddOneResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_ros_package::AddOneResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_ros_package::AddOneResponse_<ContainerAllocator>& v)
  {
    s << indent << "output: ";
    Printer<int32_t>::stream(s, indent + "  ", v.output);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_ROS_PACKAGE_MESSAGE_ADDONERESPONSE_H
