// Generated by gencpp from file my_ros_package/AddOneRequest.msg
// DO NOT EDIT!


#ifndef MY_ROS_PACKAGE_MESSAGE_ADDONEREQUEST_H
#define MY_ROS_PACKAGE_MESSAGE_ADDONEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_ros_package
{
template <class ContainerAllocator>
struct AddOneRequest_
{
  typedef AddOneRequest_<ContainerAllocator> Type;

  AddOneRequest_()
    : input(0)  {
    }
  AddOneRequest_(const ContainerAllocator& _alloc)
    : input(0)  {
  (void)_alloc;
    }



   typedef int32_t _input_type;
  _input_type input;





  typedef boost::shared_ptr< ::my_ros_package::AddOneRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_ros_package::AddOneRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AddOneRequest_

typedef ::my_ros_package::AddOneRequest_<std::allocator<void> > AddOneRequest;

typedef boost::shared_ptr< ::my_ros_package::AddOneRequest > AddOneRequestPtr;
typedef boost::shared_ptr< ::my_ros_package::AddOneRequest const> AddOneRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_ros_package::AddOneRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_ros_package::AddOneRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_ros_package::AddOneRequest_<ContainerAllocator1> & lhs, const ::my_ros_package::AddOneRequest_<ContainerAllocator2> & rhs)
{
  return lhs.input == rhs.input;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_ros_package::AddOneRequest_<ContainerAllocator1> & lhs, const ::my_ros_package::AddOneRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_ros_package

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_ros_package::AddOneRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_ros_package::AddOneRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_ros_package::AddOneRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_ros_package::AddOneRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_ros_package::AddOneRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_ros_package::AddOneRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_ros_package::AddOneRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "350f8291236c5b6fb3b8cfcb1672a02e";
  }

  static const char* value(const ::my_ros_package::AddOneRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x350f8291236c5b6fULL;
  static const uint64_t static_value2 = 0xb3b8cfcb1672a02eULL;
};

template<class ContainerAllocator>
struct DataType< ::my_ros_package::AddOneRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_ros_package/AddOneRequest";
  }

  static const char* value(const ::my_ros_package::AddOneRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_ros_package::AddOneRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 input\n"
;
  }

  static const char* value(const ::my_ros_package::AddOneRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_ros_package::AddOneRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.input);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddOneRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_ros_package::AddOneRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_ros_package::AddOneRequest_<ContainerAllocator>& v)
  {
    s << indent << "input: ";
    Printer<int32_t>::stream(s, indent + "  ", v.input);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_ROS_PACKAGE_MESSAGE_ADDONEREQUEST_H
