// Generated by gencpp from file my_ros_package/MultiplyTwoRequest.msg
// DO NOT EDIT!


#ifndef MY_ROS_PACKAGE_MESSAGE_MULTIPLYTWOREQUEST_H
#define MY_ROS_PACKAGE_MESSAGE_MULTIPLYTWOREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_ros_package
{
template <class ContainerAllocator>
struct MultiplyTwoRequest_
{
  typedef MultiplyTwoRequest_<ContainerAllocator> Type;

  MultiplyTwoRequest_()
    : a(0)
    , b(0)  {
    }
  MultiplyTwoRequest_(const ContainerAllocator& _alloc)
    : a(0)
    , b(0)  {
  (void)_alloc;
    }



   typedef int32_t _a_type;
  _a_type a;

   typedef int32_t _b_type;
  _b_type b;





  typedef boost::shared_ptr< ::my_ros_package::MultiplyTwoRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_ros_package::MultiplyTwoRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MultiplyTwoRequest_

typedef ::my_ros_package::MultiplyTwoRequest_<std::allocator<void> > MultiplyTwoRequest;

typedef boost::shared_ptr< ::my_ros_package::MultiplyTwoRequest > MultiplyTwoRequestPtr;
typedef boost::shared_ptr< ::my_ros_package::MultiplyTwoRequest const> MultiplyTwoRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_ros_package::MultiplyTwoRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_ros_package::MultiplyTwoRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_ros_package::MultiplyTwoRequest_<ContainerAllocator1> & lhs, const ::my_ros_package::MultiplyTwoRequest_<ContainerAllocator2> & rhs)
{
  return lhs.a == rhs.a &&
    lhs.b == rhs.b;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_ros_package::MultiplyTwoRequest_<ContainerAllocator1> & lhs, const ::my_ros_package::MultiplyTwoRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_ros_package

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_ros_package::MultiplyTwoRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_ros_package::MultiplyTwoRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_ros_package::MultiplyTwoRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_ros_package::MultiplyTwoRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_ros_package::MultiplyTwoRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_ros_package::MultiplyTwoRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_ros_package::MultiplyTwoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ef8322123148e475e3e93a1f609b2f70";
  }

  static const char* value(const ::my_ros_package::MultiplyTwoRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xef8322123148e475ULL;
  static const uint64_t static_value2 = 0xe3e93a1f609b2f70ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_ros_package::MultiplyTwoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_ros_package/MultiplyTwoRequest";
  }

  static const char* value(const ::my_ros_package::MultiplyTwoRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_ros_package::MultiplyTwoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 a\n"
"int32 b\n"
;
  }

  static const char* value(const ::my_ros_package::MultiplyTwoRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_ros_package::MultiplyTwoRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
      stream.next(m.b);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MultiplyTwoRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_ros_package::MultiplyTwoRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_ros_package::MultiplyTwoRequest_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<int32_t>::stream(s, indent + "  ", v.a);
    s << indent << "b: ";
    Printer<int32_t>::stream(s, indent + "  ", v.b);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_ROS_PACKAGE_MESSAGE_MULTIPLYTWOREQUEST_H
