// Generated by gencpp from file my_ros_package/MultiplyTwoResponse.msg
// DO NOT EDIT!


#ifndef MY_ROS_PACKAGE_MESSAGE_MULTIPLYTWORESPONSE_H
#define MY_ROS_PACKAGE_MESSAGE_MULTIPLYTWORESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <my_ros_package/MultiplyResult.h>

namespace my_ros_package
{
template <class ContainerAllocator>
struct MultiplyTwoResponse_
{
  typedef MultiplyTwoResponse_<ContainerAllocator> Type;

  MultiplyTwoResponse_()
    : result()  {
    }
  MultiplyTwoResponse_(const ContainerAllocator& _alloc)
    : result(_alloc)  {
  (void)_alloc;
    }



   typedef  ::my_ros_package::MultiplyResult_<ContainerAllocator>  _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::my_ros_package::MultiplyTwoResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_ros_package::MultiplyTwoResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MultiplyTwoResponse_

typedef ::my_ros_package::MultiplyTwoResponse_<std::allocator<void> > MultiplyTwoResponse;

typedef boost::shared_ptr< ::my_ros_package::MultiplyTwoResponse > MultiplyTwoResponsePtr;
typedef boost::shared_ptr< ::my_ros_package::MultiplyTwoResponse const> MultiplyTwoResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_ros_package::MultiplyTwoResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_ros_package::MultiplyTwoResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_ros_package::MultiplyTwoResponse_<ContainerAllocator1> & lhs, const ::my_ros_package::MultiplyTwoResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_ros_package::MultiplyTwoResponse_<ContainerAllocator1> & lhs, const ::my_ros_package::MultiplyTwoResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_ros_package

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_ros_package::MultiplyTwoResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_ros_package::MultiplyTwoResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_ros_package::MultiplyTwoResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_ros_package::MultiplyTwoResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_ros_package::MultiplyTwoResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_ros_package::MultiplyTwoResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_ros_package::MultiplyTwoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "92d29fa9bb1caea5b9f7ce0294895d32";
  }

  static const char* value(const ::my_ros_package::MultiplyTwoResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x92d29fa9bb1caea5ULL;
  static const uint64_t static_value2 = 0xb9f7ce0294895d32ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_ros_package::MultiplyTwoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_ros_package/MultiplyTwoResponse";
  }

  static const char* value(const ::my_ros_package::MultiplyTwoResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_ros_package::MultiplyTwoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "MultiplyResult result\n"
"\n"
"================================================================================\n"
"MSG: my_ros_package/MultiplyResult\n"
"int32 product\n"
"string message\n"
;
  }

  static const char* value(const ::my_ros_package::MultiplyTwoResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_ros_package::MultiplyTwoResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MultiplyTwoResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_ros_package::MultiplyTwoResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_ros_package::MultiplyTwoResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    s << std::endl;
    Printer< ::my_ros_package::MultiplyResult_<ContainerAllocator> >::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_ROS_PACKAGE_MESSAGE_MULTIPLYTWORESPONSE_H
