// Generated by gencpp from file my_ros_package/MultiplyResult.msg
// DO NOT EDIT!


#ifndef MY_ROS_PACKAGE_MESSAGE_MULTIPLYRESULT_H
#define MY_ROS_PACKAGE_MESSAGE_MULTIPLYRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_ros_package
{
template <class ContainerAllocator>
struct MultiplyResult_
{
  typedef MultiplyResult_<ContainerAllocator> Type;

  MultiplyResult_()
    : product(0)
    , message()  {
    }
  MultiplyResult_(const ContainerAllocator& _alloc)
    : product(0)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _product_type;
  _product_type product;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::my_ros_package::MultiplyResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_ros_package::MultiplyResult_<ContainerAllocator> const> ConstPtr;

}; // struct MultiplyResult_

typedef ::my_ros_package::MultiplyResult_<std::allocator<void> > MultiplyResult;

typedef boost::shared_ptr< ::my_ros_package::MultiplyResult > MultiplyResultPtr;
typedef boost::shared_ptr< ::my_ros_package::MultiplyResult const> MultiplyResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_ros_package::MultiplyResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_ros_package::MultiplyResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_ros_package::MultiplyResult_<ContainerAllocator1> & lhs, const ::my_ros_package::MultiplyResult_<ContainerAllocator2> & rhs)
{
  return lhs.product == rhs.product &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_ros_package::MultiplyResult_<ContainerAllocator1> & lhs, const ::my_ros_package::MultiplyResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_ros_package

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_ros_package::MultiplyResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_ros_package::MultiplyResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_ros_package::MultiplyResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_ros_package::MultiplyResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_ros_package::MultiplyResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_ros_package::MultiplyResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_ros_package::MultiplyResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9e359ab8f5ff6b1819dec7096306b3a8";
  }

  static const char* value(const ::my_ros_package::MultiplyResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9e359ab8f5ff6b18ULL;
  static const uint64_t static_value2 = 0x19dec7096306b3a8ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_ros_package::MultiplyResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_ros_package/MultiplyResult";
  }

  static const char* value(const ::my_ros_package::MultiplyResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_ros_package::MultiplyResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 product\n"
"string message\n"
;
  }

  static const char* value(const ::my_ros_package::MultiplyResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_ros_package::MultiplyResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.product);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MultiplyResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_ros_package::MultiplyResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_ros_package::MultiplyResult_<ContainerAllocator>& v)
  {
    s << indent << "product: ";
    Printer<int32_t>::stream(s, indent + "  ", v.product);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_ROS_PACKAGE_MESSAGE_MULTIPLYRESULT_H
